apiVersion: v1
kind: Service
metadata:
  name: echocube-service
spec:
  ports:
  - port: 8080
  selector:
    app: echocube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echocube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echocube
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: echocube
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: echocube
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: echocube
